# permissions for end users to edit n8ns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: n8n-operator
    app.kubernetes.io/managed-by: kustomize
  name: n8n-editor-role
rules:
- apiGroups:
  - cache.slys.dev
  resources:
  - n8ns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.slys.dev
  resources:
  - n8ns/status
  verbs:
  - get
