name: Publish to the catalog
on:
    workflow_dispatch:
jobs:
    publishing:
        name: Build Docker image and push it to the registry
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Get Current Tag (Latest)
              id: current_tag
              run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
            - name: Get Previous Tag
              id: previous_tag
              uses: WyriHaximus/github-action-get-previous-tag@v1
              with:
                fallback: 0.0.1
            - name: set VERSION env
              run: echo "VERSION=${{ steps.current_tag.outputs.tag }}" >> $GITHUB_ENV
            - name: Debug version information
              run: |
                echo "Current tag: ${{ steps.current_tag.outputs.tag }}"
                echo "Previous tag: ${{ steps.previous_tag.outputs.tag }}"
                echo "VERSION: ${{ steps.current_tag.outputs.tag }}"
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}
            - name: set CATALOG_IMG env
              run: |
                echo "CATALOG_IMG=ghcr.io/jakub-k-slys/operator-catalog:${{ steps.current_tag.outputs.tag }}" >> $GITHUB_ENV
            - name: set CATALOG_BASE_IMG env (if not first build)
              run: |
                if [ "${{ steps.previous_tag.outputs.tag }}" != "0.0.1" ] && \
                   [ "${{ steps.previous_tag.outputs.tag }}" != "${{ steps.current_tag.outputs.tag }}" ]; then
                  echo "CATALOG_BASE_IMG=ghcr.io/jakub-k-slys/operator-catalog:${{ steps.previous_tag.outputs.tag }}" >> $GITHUB_ENV
                  echo "Building catalog based on previous version: ${{ steps.previous_tag.outputs.tag }}"
                else
                  echo "Building first catalog or no previous version found, starting from scratch"
                fi
            - name: Debug catalog build configuration
              run: |
                echo "Building catalog with the following configuration:"
                echo "CATALOG_IMG: $CATALOG_IMG"
                echo "CATALOG_BASE_IMG: ${CATALOG_BASE_IMG:-not set (building from scratch)}"
                echo "VERSION: $VERSION"
            - name: Make catalog build
              run: |
                make catalog-build
            - name: Push catalog
              run: |
                make catalog-push
