name: e2e test
on:
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Running e2e tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                ci-env:
                    - '1'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '>=1.17.0'
            # - name: start minikube
            #   id: minikube
            #   uses: medyagh/setup-minikube@latest
            - name: Create k8s Kind Cluster
              uses: helm/kind-action@v1
            - name: Wait for cluster to be ready
              run: kubectl wait --for=condition=Ready pod --all -A
            - name: Try the cluster!
              run: kubectl get pods -A
            - name: set KIND_CLUSTER env
              run: echo "KIND_CLUSTER=$(kubectl config current-context)" >> $GITHUB_ENV
            - run: go version
            - name: Running e2e tests
              run: make test-e2e