name: Make a new release
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0
                  ref: ${{ github.ref_name }}
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Github registry login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              id: semantic
              with:
                  tag_format: ${version}
                  extra_plugins: |
                      @semantic-release/changelog@6.0.0
                      @semantic-release/git
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Set VERSION env
              run: echo "VERSION=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_ENV
            - run: |
                cat $VERSION > .version