name: Test
on:
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Running tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                ci-env:
                    - '1'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '>=1.17.0'
            - run: go version
            - name: Running test
              run: make test  